@ECHO OFF

PUSHD %1
FOR /R %%a in (*.sln) DO CALL :CLEAN_SOLUTION "%%~dpa"
POPD
PAUSE
GOTO :EOF

:CLEAN_SOLUTION
@ECHO CLEAN %1
PUSHD %1
FOR /R %%a in (*.*proj) DO CALL :CLEAN "%%~dpa"
POPD
GOTO :EOF

:CLEAN
CALL :REMOVEDIR "%~1obj"
CALL :REMOVEDIR "%~1bin"
CALL :DELETEFILE "%~1*_wpftmp.csproj"
GOTO :EOF

:REMOVEDIR
IF NOT EXIST %1 GOTO :EOF
@ECHO REMOVE %1
RD /s /q %1
GOTO :EOF

:DELETEFILE
IF NOT EXIST %1 GOTO :EOF
@ECHO DELETE %1
DEL %1
GOTO :EOF